DO $$ BEGIN ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'YES_NO'; EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'LEGAL_CONSENT'; EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'IRAQ_GOVERNORATE'; EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'NPS'; EXCEPTION WHEN duplicate_object THEN null; END $$;
