import type { FormTemplateDefinition } from '@/lib/form-templates/types';
import {
  applicationInternshipFields,
  applicationJobFields,
  contactBasicFields,
  contactQuoteFields,
  contactSupportFields,
  feedbackImprovementFields,
  feedbackRatingFields,
  orderProductFields,
  orderServiceFields,
  quizKnowledgeFields,
  quizShortFields,
  registrationEventFields,
  registrationWebinarFields,
  registrationWorkshopFields,
  surveyExitFields,
  surveyNpsFields,
  surveyPollFields,
  surveySatisfactionFields,
} from '@/lib/form-templates/fields';

export const FORM_TEMPLATES_CATALOG: FormTemplateDefinition[] = [
  {
    id: 'contact-basic',
    title: 'تواصل بسيط',
    description: 'نموذج تواصل أساسي: اسم، بريد، هاتف، ورسالة.',
    formType: 'CONTACT',
    category: 'business',
    tags: ['تواصل', 'دعم', 'أساسي'],
    suggestedTitle: 'تواصل معنا',
    suggestedDescription: 'يسعدنا استقبال استفساراتك ورسائلك.',
    estimatedMinutes: 2,
    featured: true,
    popular: true,
    buildFields: contactBasicFields,
  },
  {
    id: 'contact-support',
    title: 'طلب دعم فني',
    description: 'لاستقبال بلاغات الدعم مع تصنيف نوع المشكلة.',
    formType: 'CONTACT',
    category: 'customer',
    tags: ['دعم', 'تذكرة', 'مساعدة'],
    suggestedTitle: 'طلب دعم فني',
    estimatedMinutes: 3,
    buildFields: contactSupportFields,
  },
  {
    id: 'contact-quote',
    title: 'طلب عرض سعر',
    description: 'جمع بيانات العملاء المحتملين وطلبات التسعير.',
    formType: 'CONTACT',
    category: 'business',
    tags: ['مبيعات', 'عرض سعر', 'B2B'],
    suggestedTitle: 'طلب عرض سعر',
    estimatedMinutes: 3,
    popular: true,
    buildFields: contactQuoteFields,
  },
  {
    id: 'survey-nps',
    title: 'استبيان NPS',
    description: 'قياس احتمالية التوصية (Net Promoter Score).',
    formType: 'SURVEY',
    category: 'customer',
    tags: ['NPS', 'رضا', 'قياس'],
    suggestedTitle: 'استبيان NPS',
    estimatedMinutes: 2,
    featured: true,
    popular: true,
    buildFields: surveyNpsFields,
  },
  {
    id: 'survey-satisfaction',
    title: 'رضا العملاء',
    description: 'تقييم بالنجوم مع أسئلة جودة الخدمة.',
    formType: 'SURVEY',
    category: 'customer',
    tags: ['رضا', 'تقييم', 'خدمة'],
    suggestedTitle: 'استبيان رضا العملاء',
    estimatedMinutes: 3,
    buildFields: surveySatisfactionFields,
  },
  {
    id: 'survey-poll',
    title: 'استطلاع رأي',
    description: 'استطلاع سريع بخيارات متعددة.',
    formType: 'SURVEY',
    category: 'business',
    tags: ['استطلاع', 'رأي', 'سريع'],
    suggestedTitle: 'استطلاع رأي',
    estimatedMinutes: 2,
    buildFields: surveyPollFields,
  },
  {
    id: 'survey-exit',
    title: 'استبيان مغادرة',
    description: 'فهم أسباب إلغاء الاشتراك أو المغادرة.',
    formType: 'SURVEY',
    category: 'customer',
    tags: ['مغادرة', 'إلغاء', 'تحسين'],
    suggestedTitle: 'لماذا غادرت؟',
    estimatedMinutes: 2,
    buildFields: surveyExitFields,
  },
  {
    id: 'registration-event',
    title: 'تسجيل فعالية',
    description: 'تسجيل حضور فعالية مع تأكيد التاريخ.',
    formType: 'REGISTRATION',
    category: 'events',
    tags: ['فعالية', 'حضور', 'تسجيل'],
    suggestedTitle: 'تسجيل في الفعالية',
    estimatedMinutes: 3,
    featured: true,
    popular: true,
    buildFields: registrationEventFields,
  },
  {
    id: 'registration-workshop',
    title: 'تسجيل ورشة',
    description: 'ورشة عمل مع مستوى خبرة واهتمامات.',
    formType: 'REGISTRATION',
    category: 'education',
    tags: ['ورشة', 'تدريب', 'تعليم'],
    suggestedTitle: 'تسجيل ورشة عمل',
    estimatedMinutes: 3,
    buildFields: registrationWorkshopFields,
  },
  {
    id: 'registration-webinar',
    title: 'تسجيل ندوة',
    description: 'تسجيل حضور ندوة عبر الإنترنت.',
    formType: 'REGISTRATION',
    category: 'events',
    tags: ['ندوة', 'ويبينار', 'بث'],
    suggestedTitle: 'تسجيل الندوة',
    estimatedMinutes: 2,
    buildFields: registrationWebinarFields,
  },
  {
    id: 'order-product',
    title: 'طلب منتج',
    description: 'طلب منتج مع كمية وعنوان توصيل.',
    formType: 'ORDER',
    category: 'business',
    tags: ['طلب', 'منتج', 'تسوق'],
    suggestedTitle: 'طلب منتج',
    estimatedMinutes: 3,
    buildFields: orderProductFields,
  },
  {
    id: 'order-service',
    title: 'طلب خدمة',
    description: 'حجز أو طلب خدمة مع تاريخ مفضل.',
    formType: 'ORDER',
    category: 'business',
    tags: ['خدمة', 'حجز', 'صيانة'],
    suggestedTitle: 'طلب خدمة',
    estimatedMinutes: 3,
    buildFields: orderServiceFields,
  },
  {
    id: 'feedback-rating',
    title: 'تقييم بالنجوم',
    description: 'ملاحظات سريعة مع تقييم عام.',
    formType: 'FEEDBACK',
    category: 'customer',
    tags: ['تقييم', 'نجوم', 'ملاحظات'],
    suggestedTitle: 'قيّم تجربتك',
    estimatedMinutes: 2,
    featured: true,
    buildFields: feedbackRatingFields,
  },
  {
    id: 'feedback-improvement',
    title: 'اقتراح تحسين',
    description: 'استقبال أفكار واقتراحات التحسين.',
    formType: 'FEEDBACK',
    category: 'business',
    tags: ['اقتراح', 'تحسين', 'فكرة'],
    suggestedTitle: 'اقتراح تحسين',
    estimatedMinutes: 2,
    buildFields: feedbackImprovementFields,
  },
  {
    id: 'quiz-short',
    title: 'اختبار قصير',
    description: 'اختبار بسيط بأسئلة قصيرة.',
    formType: 'QUIZ',
    category: 'education',
    tags: ['اختبار', 'أسئلة', 'قصير'],
    suggestedTitle: 'اختبار قصير',
    estimatedMinutes: 3,
    buildFields: quizShortFields,
  },
  {
    id: 'quiz-knowledge',
    title: 'اختبار معرفي',
    description: 'اختبار معرفي مع إجابات متعددة.',
    formType: 'QUIZ',
    category: 'education',
    tags: ['اختبار', 'معرفة', 'تعليم'],
    suggestedTitle: 'اختبار معرفي',
    estimatedMinutes: 4,
    buildFields: quizKnowledgeFields,
  },
  {
    id: 'application-job',
    title: 'طلب توظيف',
    description: 'طلب التحاق مع رفع السيرة الذاتية.',
    formType: 'APPLICATION',
    category: 'hr',
    tags: ['توظيف', 'وظيفة', 'CV'],
    suggestedTitle: 'طلب توظيف',
    estimatedMinutes: 5,
    featured: true,
    popular: true,
    buildFields: applicationJobFields,
  },
  {
    id: 'application-internship',
    title: 'طلب تدريب',
    description: 'تقديم طلب تدريب للطلاب والخريجين.',
    formType: 'APPLICATION',
    category: 'hr',
    tags: ['تدريب', 'internship', 'HR'],
    suggestedTitle: 'طلب تدريب',
    estimatedMinutes: 4,
    buildFields: applicationInternshipFields,
  },
];
