-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LINK_CLICK';

-- AlterTable
ALTER TABLE "social_links"
  ADD COLUMN IF NOT EXISTS "scheduledStartAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "scheduledEndAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "isLocked" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "passwordHash" TEXT,
  ADD COLUMN IF NOT EXISTS "notifyOnClick" BOOLEAN NOT NULL DEFAULT false;
