export {
  isAllowedRedirectHost,
  isLoopbackHost,
  LOCAL_SERVICE_URLS,
  PRODUCTION_SERVICE_URLS,
  resolveAccountsUrl,
  resolveApiBaseUrl,
  resolveAppUrl,
  resolveBusinessUrl,
  resolveDeveloperUrl,
  resolveFormsUrl,
  resolveHqUrl,
  resolveMailUrl,
  shouldUseLocalServiceUrls,
} from '@rukny/auth/client/env-urls';
